### ISSUE TITLE
font color adjustment for dark mode 

### ISSUE THREAD

**Issue by grgprarup** [JankariTech/blog#113]
Changing the color for dark mode
**Dark Mode:**
![image](https://github.com/JankariTech/blog/assets/8559121/5885911c-6f5f-4d2f-8518-74d455f9b7b6)

**Light Mode:**
![image](https://github.com/JankariTech/blog/assets/8559121/7a8fac6b-f9f7-4746-8035-2980e2759122)

Need to check for other places too.

**Comment by koebel** [comment]
great that you noticed this! lets make sure that our website and blog is marked by high usability and accessibility :)
