### ISSUE TITLE
Search results can be empty even with valid search keywords

### ISSUE THREAD

**Issue by nabim777** [JankariTech/blog#124]
# Description
Valid search keywords are unable to give any search results in some cases, providing users with an empty result. This might be problem for the user, especially if they encounter difficulty in using the search features effectively

# Steps to reproduce
Step-1: Go to the search bar

Step-2: Search by author, assuming `artur`. It will work properly and show the results.
![image](https://github.com/JankariTech/blog/assets/61624650/8204e341-ad8c-4740-a1c1-98898bf35fb5)

Step-3: Search again with the word `arturs`, the search result will be empty, showing the message `Sorry, no results found for "arturs"` as shown in the image.
![image](https://github.com/JankariTech/blog/assets/61624650/85d7c221-1531-4fe7-bc42-148b17f409fa)

Step-4: But when we remove the `s`  from the word `arturs` using key `backspace` and become `artur` in the search results, then the search result will be empty, showing the message `Sorry, no results found for "artur"` as shown in the image.
![image](https://github.com/JankariTech/blog/assets/61624650/02163a98-95e3-41a0-bddd-18ffa24d35c5)

# Screen record
[Screencast from 04-25-2024 12:34:00 PM.webm](https://github.com/JankariTech/blog/assets/61624650/1ca358f9-f4ba-40ff-aa67-1c4ce6b4938f)

# Expected
![image](https://github.com/JankariTech/blog/assets/61624650/8204e341-ad8c-4740-a1c1-98898bf35fb5)

# Actual
![image](https://github.com/JankariTech/blog/assets/61624650/02163a98-95e3-41a0-bddd-18ffa24d35c5)

**Comment by koebel** [comment]
it seems like this only applies to https://blog.jankaritech.com, on https://dev.to/jankaritech the search seems to work properly 

When trying to reproduce this error in Chrome on Mac I also noticed that in our blog search only works for titles, it doesn't even take authors or tags into account...

**Comment by SagarGi** [comment]
> it seems like this only applies to https://blog.jankaritech.com, on https://dev.to/jankaritech the search seems to work properly
> 
> When trying to reproduce this error in Chrome on Mac I also noticed that in our blog search only works for titles, it doesn't even take authors or tags into account...

It does filter according to tags and author. And on default the search is by title. But for better user experience lets add filter by title as default filter in search? I will make an issue for that.

**Comment by SagarGi** [comment]
Hi @koebel I have created an issue here https://github.com/JankariTech/blog/issues/127. Please check if its feasible to you!
