### ISSUE TITLE
UX/UI improvement: Enhance search by filter

### ISSUE THREAD

**Issue by SagarGi** [JankariTech/blog#127]
### Description
As of now we can filter search either by tag or author and by default it does search by title. It would be better if we add an extra option to the filter `title` in UI as well and make user to search by anything as default initially.And based on filters user can search accordingly through filters so that the user knows through which filter the user is making a search. Also change the place holder of the input field based on the selection of the filter something like `search by title` , `search by tag` , `search by author`.

- [ ] Add `title` filter in UI
- [ ] Make user search anything initially 
- [ ] Make placeholder dynamic according to selected filter.

**Comment by koebel** [comment]
From a user perspective, I would expect that search is by default over all categories (title, tags, authors, ... and everything else that is technically possible) unless the user specifies that he/she only wants to search in a certain category. 

When the user selects a filter to narrow down the search, it would improve the user experience by
- displaying which filters are currently activated (not only in drop down but in some way that is more visible for the user)
- if there is no blog post that fits the search criteria, make the message clearer by saying something like "Sorry, no results found for "Go" in <search category(s)>"
- allowing a combination of multiple filters
- offer an easy way to reset all filters (something like "remove all filters")
- maybe also resetting filters when using the "reset search" button under the text of the no results message
- however for the "clear search" button I would expect that it only clears the search terms, not the filters

![image](https://github.com/JankariTech/blog/assets/8348693/8395249e-e94f-4ed3-bad7-dbf428f3f5d4)
this example shows some good ways for displaying and removing filters in a intuitive, user friendly way

If multi filter search is not possible, I agree with your suggestion to change the place holder of the input field to a text that includes the current filter. And in any case, title should also be listed as a filter in the filter dropdown

**Comment by SagarGi** [comment]
Hi @koebel For the first iteration lets managed to get what i have mentioned in the PR description. And then later we can enhance it a bit by bit in the next PRs or probably with creating new issue with your comment.

**Comment by koebel** [comment]
> Hi @koebel For the first iteration lets managed to get what i have mentioned in the PR description. And then later we can enhance it a bit by bit in the next PRs or probably with creating new issue with your comment.

I've opened a new issue for the additional suggestions
