### ISSUE TITLE
fix the home page search bar

### ISSUE THREAD

**Issue by kiranparajuli589** [JankariTech/blog#44]
the search bar should be fixed. Limitations known till now:
- [ ] Content based searches
- [ ] Tag based filtration
- [ ] More improvements for `No Results` section
- [ ] Date Based Filterations

**Comment by koebel** [comment]
I think some of the points above have been resolved in the meanwhile and others are described in more detail in the following issues:
- Enhancing search: https://github.com/JankariTech/blog/issues/139
- Sorting: https://github.com/JankariTech/blog/issues/129 (sorting search results e.g. by date)

Can we close this?
