### ISSUE TITLE
usage of external images

### ISSUE THREAD

**Issue by individual-it** [JankariTech/blog#76]
we are using a lot of external images, this is not good because
1. depending on external resources that might move
2. we might violate copyrights

ToDo:
- [ ] check the copyrights / permissions of every image
- [ ] replace images that we are not allowed to use
- [ ] mention the author where needed
- [ ] host all images on github

**Comment by SwikritiT** [comment]
I've not used external images in my blog the images are all in https://github.com/JankariTech/blog/tree/master/src/assets/Playwright/images
The banner I created myself by just using the logos of the playwright and cucumber (which i guess aren't subject to copyright)
Other pictures are screenshots of my app that I took myself. So I guess it's all clear from my side at least.

**Comment by amrita-shrestha** [comment]
NO blog post from my side
